services:
  app:
    build:
      context: .
      dockerfile: DockerfileAPP
    command: npm run start
    ports:
      - "8000:3000"
    volumes:
      - ./app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  app: