services:
  dbapp:
    build:
      context: ../
      dockerfile: DEV/Dockerfile.DB
    command: npm run migrate
    ports:
      - "8002:5002"
    volumes:
      - ../DB:/DB
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
volumes:
  DB: {}