services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - '${DB_PORT}'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 18s
      timeout: 6s
      retries: 3
  be:
    build:
      context: ../
      dockerfile: _DEV/Dockerfile.BE
    command: npm run start:dev
    ports:
      - "8001:3000"
    volumes:
      - ../BE:/BE
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
volumes:
  BE: {}
  my-db: {}