services:
  fe:
    build:
      context: ../
      dockerfile: _DEV/Dockerfile.FE
    command: npm run start
    ports:
      - "8000:3000"
    volumes:
      - ../FE:/FE
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  FE: {}